# Generated by Django 3.1.1 on 2021-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
