# Generated by Django 3.1.1 on 2021-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='y_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
