# Generated by Django 3.1.1 on 2021-03-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_contactusform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialmedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
            ],
        ),
    ]
